"""SATLIB benchmark intake (docs/current/SATLIB_BENCH_INTAKE.md, repo).

One synthetic file per defect found in data/satlib_bench/: the uuf "%"/"0"
trailer, pret's stray trailing "0", hole9's clause split across lines,
dubois100's unterminated clause lines, bf's tabs. Each must normalise to the
header's clause list, read identically by PySAT and the memetic reader, and
stay fixed under a second normalisation. Run from inside cluster_staging_maxsat/.
"""
from __future__ import annotations

import os
import sys

import pytest

STAGING = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(STAGING, "scripts"))
import satlib_bench_intake as sbi  # noqa: E402

UUF = "c gen\np cnf 3 2\n 1 -2 3 0\n-1 2 3 0\n%\n0\n\n"
PRET = "c pret\np cnf 3 2\n     1 -2 3 0\n    -1 2 3 0\n0\n"
SPLIT = "c hole\np cnf 3 2\n 1 2 0\n 3 -1\n 0\n"
UNTERMINATED = "c dubois\np cnf 3 2\n1 2 3 \n-1 -2 3  0\n"
TABS = "c bf\np cnf 3 2\n1\t-2\t0\n-3\t2\t1\t0\n"

CASES = {
    "uuf_trailer": (UUF, [(1, -2, 3), (-1, 2, 3)], "token"),
    "pret_stray_zero": (PRET, [(1, -2, 3), (-1, 2, 3)], "token"),
    "hole_split": (SPLIT, [(1, 2), (3, -1)], "token"),
    "dubois_unterminated": (UNTERMINATED, [(1, 2, 3), (-1, -2, 3)], "line"),
    "bf_tabs": (TABS, [(1, -2), (-3, 2, 1)], "token"),
}


@pytest.mark.parametrize("name", sorted(CASES))
def test_normalise_recovers_header_clauses(name):
    text, want, reading = CASES[name]
    new, p = sbi.normalise(text)
    assert p["clauses"] == want
    assert p["reading"] == reading
    assert "c normalized (scripts/satlib_bench_intake.py)" in new
    assert sbi.pysat_clauses(new) == want
    assert sbi.memetic_clauses(new) == want
    assert sbi.normalise(new)[0] == new


def test_pysat_misreads_originals():
    # The reason for normalising: PySAT's line reader turns these into empty clauses.
    assert () in sbi.pysat_clauses(UUF)
    assert () in sbi.pysat_clauses(PRET)
    assert () in sbi.pysat_clauses(SPLIT)
    # and silently drops the last literal of an unterminated line (dubois100)
    assert sbi.pysat_clauses(UNTERMINATED) == [(1, 2), (-1, -2, 3)]


def test_canonical_file_is_left_alone():
    text = "c ok\np cnf 2 1\n1 -2 0\n"
    new, p = sbi.normalise(text)
    assert new == text and p["notes"] == []


def test_header_mismatch_is_an_error():
    with pytest.raises(ValueError, match="no reading matches"):
        sbi.normalise("p cnf 3 3\n1 2 0\n-1 3 0\n")
    with pytest.raises(ValueError, match="no reading matches"):
        sbi.normalise("p cnf 2 1\n1 7 0\n")  # variable beyond n


@pytest.mark.parametrize("family,comments,want", [
    ("dubois", ["c NOTE: Not satisfiable"], ("unsat", "file_note")),
    ("jnh", ["c NOTE: Satisfiable"], ("sat", "file_note")),
    ("pret", ["c        Charge ( 0 = sat. / 1 = unsat. ) ==>    1"], ("unsat", "file_generator_field")),
    ("pret", ["c        Charge ( 0 = sat. / 1 = unsat. ) ==>    0"], ("sat", "file_generator_field")),
    ("uuf200", ["c This Formular is generated by mcnf"], ("unsat", "family_convention")),
    ("bf", ["c FILE:  bf0432-007.cnf"], ("unsat", "family_convention")),
    ("other", ["c nothing"], ("unknown", "none")),
])
def test_label(family, comments, want):
    assert sbi.label(family, comments)[:2] == want


def test_note_wins_over_family_convention():
    # an explicit file note is read before any family default
    assert sbi.label("uuf200", ["c NOTE: Satisfiable"])[:2] == ("sat", "file_note")
